import { createClient } from "@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
if(!url||!key) console.warn("أضف متغيرات Supabase في .env");
export const supabase=createClient(url||"https://placeholder.supabase.co",key||"placeholder");
export const getSession=async()=>{const {data}=await supabase.auth.getSession();return data.session};
export const signUpUser=(email,password,full_name,role)=>supabase.auth.signUp({email,password,options:{data:{full_name,role}}});
export const signInUser=(email,password)=>supabase.auth.signInWithPassword({email,password});
export const signOutUser=()=>supabase.auth.signOut();
export const getProducts=(category="")=>{let q=supabase.from("products").select("id,store_id,name,description,category,price,image_url,stock,active,created_at,stores(id,name,logo_url)").eq("active",true).order("created_at",{ascending:false});return category?q.eq("category",category):q};
export const getMyStores=(ownerId)=>supabase.from("stores").select("*").eq("owner_id",ownerId).order("created_at",{ascending:false});
export const createStore=(owner_id,name,description,logo_url)=>supabase.from("stores").insert({owner_id,name,description,logo_url:logo_url||null}).select().single();
export const getMyProducts=(ids)=>ids?.length?supabase.from("products").select("*,stores(id,name)").in("store_id",ids):Promise.resolve({data:[],error:null});
export const createProduct=(p)=>supabase.from("products").insert(p).select().single();